Revert "[bot] [main] Automated dependencies update"
because the prometheus pods no longer start on meta-clusters due to error
message: create Pod prometheus-k8s-0 in StatefulSet prometheus-k8s failed
error: pods "prometheus-k8s-0" is forbidden: PodSecurityPolicy: unable
to admit pod: [spec.volumes[1]: Invalid value: "projected": projected
volumes are not allowed to be used]

This reverts commit 2c328aabc928158f78b66092fca1d91bac0416ae.